### ISSUE TITLE
Using legacy `offerToReceiveVideo` in step 2

### ISSUE THREAD

**Issue by lolaodelola** [googlecodelabs/webrtc-web#119]
```javascript
const offerOptions = {
  offerToReceiveVideo: 1,
};
```
According to MDN, `offerToReceiveVideo` is legacy and should be replaced with `RTCRtpTransceiver`,

>You shouldn't use this legacy property. Instead, use `RTCRtpTransceiver` to control whether or not to accept incoming video.
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createOffer

**Comment by thegiantbeast** [comment]
Just an update on this issue, `createOffer` page on MDN was updated twice after this issue was created.
One to remove any reference to `offerToReceiveVideo` and `offerToReceiveAudio`.
And then another update to reintroduce them as deprecated options. But its missing the note section about `RTCRtpTransceiver`, so I've added a comment to see if it can be reintroduced https://github.com/mdn/content/issues/12164#issuecomment-1042480783
